/**
 * Type definitions for tree detection API
 * These interfaces define the contract between frontend and Python backend
 */

/**
 * HSV color thresholds for tree detection
 * Note: OpenCV uses H: 0-179, S: 0-255, V: 0-255
 * Frontend may display H: 0-360, S: 0-100, V: 0-100 (conversion needed)
 */
export interface HSVThresholds {
  hue: { min: number; max: number };
  saturation: { min: number; max: number };
  value: { min: number; max: number };
}

/**
 * Detection parameters for tree size constraints and clustering
 */
export interface DetectionParameters {
  minTreeDiameter: number;    // meters
  maxTreeDiameter: number;    // meters
  clusterThreshold: number;   // meters - circles > this diameter are clusters
}

/**
 * Real-world image dimensions for coordinate conversion
 */
export interface ImageDimensions {
  width: number;   // meters
  height: number;  // meters
}

/**
 * Tree polygon contour points in both pixel and meter coordinates
 */
export interface TreePolygon {
  polygonPx: number[][];   // [[x, y], [x, y], ...] in pixels
  polygonM: number[][];    // [[x, y], [x, y], ...] in meters
}

/**
 * Individual detected tree
 */
export interface IndividualTree extends TreePolygon {
  type: 'individual';
  centroidPx: [number, number];      // [x, y] in pixels
  centroidM: [number, number];       // [x, y] in meters
  areaM2: number;                    // area in square meters
  estimatedDiameterM: number;        // diameter calculated from area
}

/**
 * Tree within a cluster (generated by populate_cluster algorithm)
 */
export interface PopulatedTree {
  positionPx: [number, number];      // [x, y] in pixels
  positionM: [number, number];       // [x, y] in meters
  estimatedDiameterM: number;        // diameter in meters
}

/**
 * Tree cluster with populated trees inside
 */
export interface TreeCluster extends TreePolygon {
  type: 'cluster';
  areaM2: number;                    // total cluster area
  centroidPx: [number, number];      // cluster center in pixels
  centroidM: [number, number];       // cluster center in meters
  populatedTrees: PopulatedTree[];   // trees generated within cluster
}

/**
 * Complete tree detection result from Python API
 */
export interface TreeDetectionResult {
  metadata: {
    timestamp: string;
    sourceImage: string;
    imageDimensionsPx: { width: number; height: number };
    realDimensionsM: { width: number; height: number };
    metersPerPixel: { x: number; y: number };
    hsvRange: {
      lower: [number, number, number];   // [H, S, V]
      upper: [number, number, number];   // [H, S, V]
    };
    detectionParameters: DetectionParameters;
  };
  summary: {
    individualTreesCount: number;
    treeClustersCount: number;
    totalPopulatedTrees: number;       // sum of all populated trees in clusters
  };
  individualTrees: IndividualTree[];
  treeClusters: TreeCluster[];
  maskImageUrl?: string;                // Base64 data URL or blob URL to mask overlay
}

/**
 * Error response from tree detection API
 */
export interface DetectionError {
  error: string;
  message: string;
  details?: unknown;
}
